import Head from 'next/head'
import Image from 'next/image'
import Post from '../components/Post/Post';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>SH-Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-5">
        <Post />
        <Post />
        <Post />
      </main>
    </div>
  );
}
